### ISSUE TITLE
Translator unit tests are failing with latest commit

### ISSUE THREAD

**Issue by ahives** [phatboyg/Machete#33]
1) Failed : Machete.HL7.Tests.Using_an_empty_translate.Should_simply_match_the_input
  Expected: True
  But was:  False
@phatboyg getting below unit tests failing with your latest commit.

at Machete.HL7.Tests.Using_an_empty_translate.<Should_simply_match_the_input>d__0.MoveNext() in C:\projects\machete\src\Machete.HL7.Tests\Translate_Specs.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
at NUnit.Framework.Internal.Commands.TestMethodCommand.RunAsyncTestMethod(TestExecutionContext context)
2) Failed : Machete.HL7.Tests.Using_an_empty_translate.Should_support_value_list_properties
  Expected: True
  But was:  False
at Machete.HL7.Tests.Using_an_empty_translate.<Should_support_value_list_properties>d__1.MoveNext() in C:\projects\machete\src\Machete.HL7.Tests\Translate_Specs.cs:line 71
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
at NUnit.Framework.Internal.Commands.TestMethodCommand.RunAsyncTestMethod(TestExecutionContext context)

**Comment by phatboyg** [comment]
Still haven't done this yet.

**Comment by ahives** [comment]
@phatboyg Is this still valid?

**Comment by phatboyg** [comment]
Yeah, I don't have the work finished yet.
