### ISSUE TITLE
NuGet package available?

### ISSUE THREAD

**Issue by StefanoD** [phatboyg/Machete#52]
Hi,
is there a nuget package available? I can't build Machete. I get following error.

```
C:\Program Files\Git\cmd\git.exe status -s -b
System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.ArgumentException: The input sequence was empty.
Parametername: source
   bei Microsoft.FSharp.Collections.SeqModule.Head[T](IEnumerable`1 source)
   bei Fake.Git.Information.getBranchName(String repositoryDir) in D:\code\fake\src\app\FakeLib\Git\Information.fs:Zeile 51.
   bei FSI_0005.Build.informationalVersion[a](a _arg1)
   bei <StartupCode$FSI_0005>.$FSI_0005_Build$fsx.main@()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   bei System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   bei Fake.FSIHelper.runScriptCached@315.Invoke(Unit unitVar0) in D:\code\fake\src\app\FakeLib\FSIHelper.fs:Zeile 323.
System.Exception: Start of process git.exe failed. Das System kann die angegebene Datei nicht finden
   at Fake.ProcessHelper.ExecProcessWithLambdas@103-16.Invoke(String message) in D:\code\fake\src\app\FakeLib\ProcessHelper.fs:line 103
   at Fake.ProcessHelper.ExecProcessWithLambdas(FSharpFunc`2 configProcessStartInfoF, TimeSpan timeOut, Boolean silent, FSharpFunc`2 errorF, FSharpFunc`2 messageF) in D:\code\fake\src\app\FakeLib\ProcessHelper.fs:line 103
   at Fake.ProcessHelper.ExecProcessAndReturnMessages(FSharpFunc`2 configProcessStartInfoF, TimeSpan timeOut) in D:\code\fake\src\app\FakeLib\ProcessHelper.fs:line 130
   at Fake.Git.CommandHelper.runGitCommand(String repositoryDir, String command) in D:\code\fake\src\app\FakeLib\Git\CommandHelper.fs:line 28
   at Fake.Git.Information.getBranchName(String repositoryDir) in D:\code\fake\src\app\FakeLib\Git\Information.fs:line 51
   at FSI_0005.Build.informationalVersion[a](a _arg1) in D:\development\HL7MacheteLibTest\Machete\build.fsx:line 28
   at <StartupCode$FSI_0005>.$FSI_0005_Build$fsx.main@() in D:\development\HL7MacheteLibTest\Machete\build.fsx:line 40
Stopped due to error
```

**Comment by phatboyg** [comment]
Yes, check NuGet. Search for Machete.

**Comment by StefanoD** [comment]
Sorry, I asked, because the only package I've found for .Net Core 2.0 is `Machete.Catalog.Contracts`.

**Comment by phatboyg** [comment]
https://www.nuget.org/packages/Machete.NET/1.0.219-develop

**Comment by StefanoD** [comment]
I see, I have to look for preview versions. Thx!

**Comment by StefanoD** [comment]
Is there any documentation?

**Comment by phatboyg** [comment]
Haha. That's funny.

https://gitter.im/PhatBoyG-Machete/Lobby

**Comment by dominiqueplante** [comment]
@StefanoD - take a look at the unit tests
